server:
  port: 8086

service:
  session:
    host: 37.46.134.43
    port: 8084
    clientId: gateway
    secret: secret

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    drug_service:
      path: /api/1.0/**/drug/**
      url: http://37.46.134.43:8080/api/1.0

    patient_service:
      path: /api/1.0/**/patient/**
      url: http://37.46.134.43:8081/api/1.0

    recommendation_service:
      path: /api/1.0/**/recommendation/**
      url: http://37.46.134.43:8082/api/1.0

    profile_service:
      path: /api/1.0/**/profile/**
      url: http://37.46.134.43:8083/api/1.0

    analyzer_service:
      path: /api/1.0/**/analyzer/**
      url: http://37.46.134.43:8087/api/1.0

    session_service:
      path: /oauth/**
      url: http://37.46.134.43:8084/oauth

    login:
      path: /login/**
      url: http://37.46.134.43:8084/login

    logout:
      path: /logout/**
      url: http://37.46.134.43:8084/logout

    registration:
      path: /registration/**
      url: http://37.46.134.43:8084/registration

