server:
  port: 8086

service:
  session:
    host: session-service
    port: 8084
    clientId: gateway
    secret: secret

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    drug_service:
      path: /api/1.0/**/drug/**
      url: drug-service:8080/api/1.0

    patient_service:
      path: /api/1.0/**/patient/**
      url: patient-service:8081/api/1.0

    recommendation_service:
      path: /api/1.0/**/recommendation/**
      url: recommendation-service:8082/api/1.0

    profile_service:
      path: /api/1.0/**/profile/**
      url: profile-service:8083/api/1.0

    session_service:
      path: /oauth/**
      url: session-service:8084/oauth

    login:
      path: /login/**
      url: session-service:8084/login

    logout:
      path: /logout/**
      url: session-service:8084/logout

    registration:
      path: /registration/**
      url: session-service:8084/registration

