server:
  port: 8086

service:
  session:
    host: 79.174.13.21
    port: 8084
    clientId: gateway
    secret: secret

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    drug_service:
      path: /api/1.0/**/drug/**
      url: http://drug-service/api/1.0

    patient_service:
      path: /api/1.0/**/patient/**
      url: http://patient-service/api/1.0

    recommendation_service:
      path: /api/1.0/**/recommendation/**
      url: http://recommendation-service/api/1.0

    profile_service:
      path: /api/1.0/**/profile/**
      url: http://profile-service/api/1.0

    session_service:
      path: /oauth/**
      url: http://session-service/oauth

    login:
      path: /login/**
      url: http://session-service/login

    logout:
      path: /logout/**
      url: http://session-service/logout

    registration:
      path: /registration/**
      url: http://session-service/registration

